[package]
name = "marwans-schedule"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
ms-core = { path = "../../core" }
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-global-shortcut = "2"
tauri-plugin-autostart = "2"
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
iana-time-zone.workspace = true
rusqlite.workspace = true
