//! Moving one occurrence of a repeat, and putting it back.
//!
//! A recurring occurrence is not a row — it is generated on read — so moving
//! one is two writes: an exception on that date, and a real placement at the
//! new time. Both or neither.

use chrono::NaiveDate;
use chrono_tz::America::Chicago;
use ms_core::{add_from_text_in, get_week, move_occurrence, restore_occurrence, Db, Origin};

fn d(s: &str) -> NaiveDate {
    NaiveDate::parse_from_str(s, "%Y-%m-%d").unwrap()
}

fn now() -> chrono::DateTime<chrono::Utc> {
    "2026-08-31T12:00:00Z".parse().unwrap()
}

/// A class every Monday and Wednesday, 10:30–12:00.
fn class(db: &Db) -> ms_core::Item {
    add_from_text_in(db, "PHYS201 every mon wed 10:30-12:00", d("2026-08-31"), now(), Chicago)
        .unwrap()
}

fn placements_on(db: &Db, date: &str) -> Vec<ms_core::Placement> {
    let week = get_week(db, d("2026-08-31"), Chicago);
    week.days.into_iter().find(|day| day.date == d(date)).map(|day| day.placements).unwrap()
}

#[test]
fn moving_one_occurrence_leaves_the_series_alone() {
    let db = Db::open_in_memory().unwrap();
    let item = class(&db);

    move_occurrence(
        &db,
        &item.id,
        d("2026-09-02"),
        "2026-09-02T14:00:00-05:00",
        "2026-09-02T15:30:00-05:00",
    )
    .unwrap();

    let moved = placements_on(&db, "2026-09-02");
    assert_eq!(moved.len(), 1, "still exactly one block that day: {moved:?}");
    assert_eq!(moved[0].starts_at.format("%H:%M").to_string(), "14:00");
    assert_eq!(moved[0].origin, Origin::Moved, "and it knows it was moved");
    assert_eq!(moved[0].moved_from, Some(d("2026-09-02")));

    let monday = placements_on(&db, "2026-08-31");
    assert_eq!(monday.len(), 1, "Monday is untouched");
    assert_eq!(monday[0].starts_at.format("%H:%M").to_string(), "10:30");

    // And the week after is still generated from the rule.
    let next = get_week(&db, d("2026-09-07"), Chicago);
    let next_wed = &next.days[2];
    assert_eq!(next_wed.placements.len(), 1, "next Wednesday is still 10:30");
    assert_eq!(next_wed.placements[0].starts_at.format("%H:%M").to_string(), "10:30");
}

#[test]
fn restoring_removes_the_moved_copy() {
    let db = Db::open_in_memory().unwrap();
    let item = class(&db);
    move_occurrence(
        &db,
        &item.id,
        d("2026-09-02"),
        "2026-09-02T14:00:00-05:00",
        "2026-09-02T15:30:00-05:00",
    )
    .unwrap();

    restore_occurrence(&db, &item.id, d("2026-09-02")).unwrap();

    let back = placements_on(&db, "2026-09-02");
    assert_eq!(back.len(), 1, "the class is back once, not twice: {back:?}");
    assert_eq!(back[0].starts_at.format("%H:%M").to_string(), "10:30");
    assert_eq!(back[0].origin, Origin::Recurrence, "generated by the rule again");
}

#[test]
fn moving_the_same_occurrence_twice_does_not_duplicate_it() {
    let db = Db::open_in_memory().unwrap();
    let item = class(&db);
    for hour in ["14:00", "16:00"] {
        move_occurrence(
            &db,
            &item.id,
            d("2026-09-02"),
            &format!("2026-09-02T{hour}:00-05:00"),
            &format!("2026-09-02T{hour}:00-05:00").replace(hour, "17:30"),
        )
        .ok();
    }
    let after = placements_on(&db, "2026-09-02");
    assert_eq!(after.len(), 1, "one block, wherever it ended up: {after:?}");
}

#[test]
fn a_move_that_cannot_be_placed_writes_nothing() {
    let db = Db::open_in_memory().unwrap();
    let item = class(&db);

    let bad = move_occurrence(
        &db,
        &item.id,
        d("2026-09-02"),
        "2026-09-02T14:00:00-05:00",
        "2026-09-02T13:00:00-05:00", // ends before it starts
    );
    assert!(bad.is_err(), "an end before the start is refused");

    let untouched = placements_on(&db, "2026-09-02");
    assert_eq!(untouched.len(), 1, "the occurrence is still there");
    assert_eq!(untouched[0].origin, Origin::Recurrence, "and still comes from the rule");
    assert_eq!(
        untouched[0].starts_at.format("%H:%M").to_string(),
        "10:30",
        "a refused move must not have cancelled the date"
    );
}

#[test]
fn moving_something_that_does_not_repeat_is_refused() {
    let db = Db::open_in_memory().unwrap();
    let item =
        add_from_text_in(&db, "renew parking", d("2026-08-31"), now(), Chicago).unwrap();
    let r = move_occurrence(
        &db,
        &item.id,
        d("2026-09-02"),
        "2026-09-02T14:00:00-05:00",
        "2026-09-02T15:00:00-05:00",
    );
    assert!(r.is_err(), "there is no occurrence to move");
}
